[package]
name = "kyber"
version = "0.2.0-alpha"
authors = ["quininer kel <quininer@live.com>"]
description = "a CCA-secure module-lattice-based KEM"
repository = "https://github.com/quininer/kyber"
license = "MIT"

[features]
default = [ "kyber768" ]
kyber512 = []
kyber768 = []
kyber1024 = []

[dependencies]
rand = "0.4"
sha3 = "0.7"
digest = "0.7"
subtle = "0.3"
arrayref = "0.3"
byteorder = "1.1"
itertools = "0.7"

[dev-dependencies]
hex = "0.3"
