[package]
name = "kyber"
version = "0.2.0-alpha"
authors = ["quininer kel <quininer@live.com>"]
description = "a CCA-secure module-lattice-based KEM"
repository = "https://github.com/quininer/kyber"
license = "MIT"

[features]
default = [ "kyber768" ]
kyber512 = []
kyber768 = []
kyber1024 = []

[dependencies]
rand = "0.3"
sha3 = "0.6"
digest = "0.6"
tiny-keccak = "1.3"
byteorder = "1.1"
itertools = "0.7"

[dev-dependencies]
rustc-hex = "1.0"
