[package]
name = "kyber"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]
description = "a CCA-secure module-lattice-based KEM"
repository = "https://github.com/quininer/kyber"
license = "MIT"

[features]
default = [ "kyber512" ]
kyber512 = []
kyber768 = []
kyber1024 = []

[dependencies]
rand = "0.3"
tiny-keccak = "1.3"
byteorder = "1.1"
itertools = "0.7"

[dev-dependencies]
data-encoding = "2.0.0-rc"
