[package]
name = "kyber"
version = "0.1.0"
authors = ["quininer kel <quininer@live.com>"]

[dependencies]
rand = "*"
tiny-keccak = "*"
sp800-185 = "*"
byteorder = "*"

[dev-dependencies]
data-encoding = "2.0.0-rc"
